### ISSUE TITLE
Fracciones Arancelarias 2021

### ISSUE THREAD

**Issue by valhallaws** [phpcfdi/resources-sat-catalogs#1]
El SAT cambió las fracciones para Complemento de Comercio Exterior, agregó dos dígitos. Recién descubro su librería y es una maravilla. Será posible contar con alguna actualización?

**Comment by eclipxe13** [comment]
Ya estoy trabajando en ello pero aun no tengo una solución.

Este repositorio de recursos se alimenta gracias a la herramienta `phpcfdi/sat-catalogos-populate` y ahí puse un issue el día de ayer: https://github.com/phpcfdi/sat-catalogos-populate/issues/1

Si puedes, ahí podemos seguir el hilo de la conversación. Me interesa conocer tu opinión con respecto al punto: *¿Se va a utilizar la misma tabla de fracciones arancelarias o se usará una nueva?*

**Comment by eclipxe13** [comment]
Ya se solucionó este problema y se hizo la actualización automática en el commit https://github.com/phpcfdi/resources-sat-catalogs/commit/61fd79264688bbcf8d5be6d6ac2910758834fd33
